### ISSUE TITLE
foldering problem

### ISSUE THREAD

**Issue by eyazdpour** [TestHubTM/proudScreen#2]
Let's have a name for each site and then we can provide a "read.me" for each screenshot group so that there can be separated folders for each group and information like the site address and time can be included in the "read.me" of each folder.
Also we can specify the saving directory with another parameter for the SS function.

SS function can have 3 overloads:

1. SS(siteAddress, projectName, savingDirectory)
2. SS(siteAddress, savingDirectory) : [project name will be the same as site address]
3. SS(siteAddress) : [saving directory will be the root of the project]

**Comment by pmzi** [comment]
problem solved in [this ](https://github.com/TestHubTM/proudScreen/commit/0eb6dfa22496b373dd137332784ebc62a47a38cc)commit;)
